version: '3'

services:
  db:
    restart: always
    image: postgres:latest
    ports:
      - 5555:5432
    environment:
      TZ: Europe/Moscow
      POSTGRES_USER: cloud-box
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cloud_box
